START : 2018-09-10 20:37:43

                INSERT INTO TR_HO_SUMMARY_OUTLOOK (
                    PERIOD_BUDGET,
                    CC_CODE,
                    COA_CODE,
                    ACT_JAN,
                    ACT_FEB,
                    ACT_MAR,
                    ACT_APR,
                    ACT_MAY,
                    ACT_JUN,
                    ACT_JUL,
                    ACT_AUG,
                    OUTLOOK_SEP,
                    OUTLOOK_OCT,
                    OUTLOOK_NOV,
                    OUTLOOK_DEC,
                    ADJ,
                    YTD_ACTUAL_ADJ,
                    OUTLOOK,
                    LATEST_PERIOD,
                    ANNUALIZED_YTD,
                    VARIANCE_RP,
                    VARIANCE_PERSEN,
                    INSERT_USER,
                    INSERT_TIME
                ) VALUES (
                    TO_DATE('2018', 'YYYY'),
                    '015',
                    '7101010501',
                    '2955411034',
                    '0',
                    '0',
                    '-94826115',
                    '0',
                    '0',
                    '4552945',
                    '0',
                    '0',
                    '0',
                    '0',
                    '0',
                    '94826115',
                    '2959963979',
                    '0',
                    '2959963979',
                    '4439945968.5',
                    '-1432568932',
                    '-33.33',
                    'MUHAMMAD.RIZALDY',
                    CURRENT_TIMESTAMP
                );
            