<?PHP
header("Content-type: text/csv");
header("Content-Disposition: attachment; filename=template_upload_perencanaan_produksi_".date("YmdHis").".csv");
header("Pragma: no-cache");
header("Expires: 0");

echo "REGION_CODE,BUSINESS AREA,AFDELING,KODE BLOK,LAND SUITABILITY,LAND TYPE,JENIS BIBIT,TAHUN TANAM,BULAN TANAM,";
echo "TANAM_HA,TANAM_POKOK,TANAM_SPH,";
echo "HA_PANEN,POKOK_PRODUKTIF,SPH_PRODUKTIF,";
echo "TON_AKTUAL,JANJANG_AKTUAL,BJR_AKTUAL,YPH_AKTUAL,";
echo "TON_TAKSASI,JANJANG_TAKSASI,BJR_TAKSASI,YPH_TAKSASI,";
echo "ANTISIPASI_TON,ANTISIPASI_JJG,ANTISIPASI_BJR,ANTISIPASI_YPH,";
echo "BUDGET_TON,BUDGET_YPH,VAR_YPH,";
echo "PERIODE_BUDGET_SMS1_HA,PERIODE_BUDGET_SMS1_POKOK,PERIODE_BUDGET_SMS1_SPH,";
echo "PERIODE_BUDGET_SMS2_HA,PERIODE_BUDGET_SMS2_POKOK,PERIODE_BUDGET_SMS2_SPH,";
echo "YIELD_PROFILE_YPH,YIELD_PROFILE_TON,POTENSI_YPH,POTENSI_TON,";
echo "BUDGET_JJG,BUDGET_BJR,BUDGET_TON,BUDGET_YPH,";
echo "DISTRIBUSI_JAN,DISTRIBUSI_FEB,DISTRIBUSI_MAR,DISTRIBUSI_APR,DISTRIBUSI_MEI,DISTRIBUSI_JUN,";
echo "DISTRIBUSI_JUL,DISTRIBUSI_AGS,DISTRIBUSI_SEP,DISTRIBUSI_OKT,DISTRIBUSI_NOV,DISTRIBUSI_DES,";
echo "DISTRIBUSI_SMS1,DISTRIBUSI_SMS2,JARAK_PKS,PERSEN_LANGSIR";
echo "\n";

foreach($this->data['rows'] as $idx => $row){
	echo $row['REGION_CODE'].",";
	echo $row['BA_CODE'].",";
	echo $row['AFD_CODE'].",";
	echo $row['BLOCK_CODE'].",";
	echo $row['LAND_SUITABILITY'].",";
	echo $row['LAND_TYPE'].",";
	echo $row['PROGENY'].",";
	echo $row['YEAR_PLANT'].",";
	echo $row['MONTH_PLANT'].",";
	echo $row['HA_PLANTED'].",";
	echo $row['POKOK_TANAM'].",";
	echo $row['SPH'].",";
	echo $row['JARAK_PKS'].",";
	echo $row['PERSEN_LANGSIR']."\n";
}
?>